### ISSUE TITLE
INVALID when disassembling insertps

### ISSUE THREAD

**Issue by reliasn** [zyantific/zyan-disassembler-engine#4]
Tried to disassemble this 32-bit buffer in the SimpleDemo.cpp sample:
```
{ 0x66, 0x0F, 0x3A, 0x21, 0xD0, 0xF0, 0x33, 0xC0 }
```
Zydis fails to find the correct instruction: 
```
insertps xmm2, xmm0, 0F0h
```
Also tested with Udis86 and it failed as well.

Debugged a little, and it fails in InstructionDecoder::decodeOperands function, which is inside InstructionDecoder::decodeOpcode.

In the above case, it managed to correctly disassemble the next instruction (xor eax, eax):
```
77091852 db 66
77091853 db 0F
77091854 cmp ah, [ecx]
77091856 shl al, 01
77091858 xor eax, eax
```
But I was wondering if it's better to skip the entire insertps instruction instead of skipping only 1 byte and trying to disassemble it. For that, you would need to get at least the insertps instruction length correctly.

**Comment by flobernd** [comment]
Thanks for your detailed bug report. The "insertps" instruction is now recognized correctly.
